version: "3.9"

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: GenAI_Jenkins
    user: root
    ports:
      - "8888:8080"
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./dockerfile:/dockerfile
      - ./source:/source
      - ./data:/data
      - ./logs:/logs
    restart: always

  ml:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    container_name: GenAI_POC_Finance
    volumes:
      - ./source:/source
      - ./data:/data
      - ./logs:/logs
    env_file:
      - ./.env
    environment:
      - DATABASE_PATH=/data/database.db
    restart: always

  app:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.app
    container_name: GenAI_App
    ports:
      - "8501:8501"
    volumes:
      - ./source:/source
      - ./data:/data
      - ./logs:/logs
    env_file:
      - ./.env
    environment:
      - DATABASE_PATH=/data/database.db
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: GenAI_MLFLOW
    ports:
      - "8083:8082"
    volumes:
      - ./Mlflow:/mlruns       
      - ./logs:/logs
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db  
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 8082
    restart: always

  trainer:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.train
    container_name: GenAI_Trainer
    depends_on:
      - mlflow
    volumes:
      - ./Mlflow:/app/mlflow_artifacts   
      - ./logs:/logs
    env_file:
      - ./.env
    environment:
      - DATABASE_PATH=/data/database.db
      - MLFLOW_TRACKING_URI=http://mlflow:8082
    command: ["python", "/app/train_mlflow.py"]  
    restart: "no"

  data:
    image: alpine
    container_name: GenAI_Data
    volumes:
      - ./data:/data
      - ./logs:/logs
    command: tail -f /dev/null
