
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl git && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY Mlflow/train_mlflow.py .

ENV MLFLOW_TRACKING_URI=http://mlflow:8082

CMD ["python", "train_mlflow.py"]

